services:
  - type: web
    name: exoplanets
    env: python
    buildCommand: pip install --only-binary=:all: -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0